### ISSUE TITLE
binary panic

### ISSUE THREAD

**Issue by inetman28** [jenningsloy318/panos_exporter#11]
Hi

PAN 5260
OS 10.1.3

I got next output when I had ran your app in my test env for testing:

```

root@2dc6029ef798:/app# ./build/panos_exporter --config.file=panos_exporter.yaml
INFO[0000] panos_exporter version 0.10.0, build reversion 7233dea808a083f503de00236846d1a4a76d34ae, build branch master, build at 2022-09-13 16:29:51+00:00 on host 2dc6029ef798  source="main.go:67"
INFO[0000] Starting panos_exporter                       source="main.go:74"
INFO[0000] Loaded config file                            source="config.go:43"
INFO[0000] Listening on :9654                            source="main.go:99"
INFO[0001] Scraping target 10.10.10.242                source="main.go:38"
panic: runtime error: slice bounds out of range [:15] with capacity 0

goroutine 53 [running]:
github.com/jenningsloy318/panos_exporter/collector.(*ReportCollector).collectTopBlockedWebsites(0x4000028ff0, 0x4000121040?, {0x5fed10?, 0x4000121500?})
	/app/collector/reports_collector.go:71 +0x354
github.com/jenningsloy318/panos_exporter/collector.(*ReportCollector).Collect(0x4000028ff0, 0x0?)
	/app/collector/reports_collector.go:54 +0x94
github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect.func1({0x5fc950?, 0x4000028ff0?})
	/app/collector/panos_collector.go:105 +0x64
created by github.com/jenningsloy318/panos_exporter/collector.(*PanosCollector).Collect
	/app/collector/panos_collector.go:103 +0x274
root@2dc6029ef798:/app#
```

it seems that app doesnt process an error

**Comment by zbbfufu** [comment]
Hi,

Thanks for the report.
This error happens when there is no top blocked website on your PAN OS.
I expect to have time to fix it by the end of September.

Regards,
Julien

**Comment by inetman28** [comment]
Thanks a lot.

вт, 13 сент. 2022 г., 22:15 Julien Furgerot ***@***.***>:

**Comment by Alfredo-Moreira** [comment]
Any ETA on this? Running into this issue as well. Thank you for publishing the library!

**Comment by zbbfufu** [comment]
Hi Alfredo,
This task get delayed by other at work, but it is finally next on my todo list. I expect to fix it on next week (Oct. 21).

**Comment by Alfredo-Moreira** [comment]
Thank you for the update!

**Comment by zbbfufu** [comment]
The fix is developed. It's in review in my company, it will be released before end of week.

**Comment by zbbfufu** [comment]
This bug is fixed, you can pull Docker image here:
https://github.com/users/jenningsloy318/packages/container/panos_exporter/46259392?tag=v0.10.1
